name: Build and deploy Python app to Azure Web App - blogging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Identify changed files
        id: changed-files
        run: |
          git diff --name-only HEAD^ HEAD > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt

      - name: Package changed files and essentials
        run: |
          mkdir -p release
          # Copy only changed files and their dependencies (if needed)
          while IFS= read -r file; do
            if [ -f "$file" ]; then
              mkdir -p "release/$(dirname "$file")"
              cp "$file" "release/$file"
              # If a Python file changes, include dependent files (e.g., imports from src/)
              if [[ "$file" == *.py ]]; then
                grep -h "^import " "$file" | while read -r import_line; do
                  import_name=$(echo "$import_line" | awk '{print $2}' | cut -d'.' -f1)
                  find src/ -name "$import_name.py" -exec cp --parents {} release/ \;
                done
              fi
            fi
          done < changed_files.txt
          # Always copy requirements.txt and key app files to ensure Azure detects the Python app
          cp -n requirements.txt release/  # -n avoids overwriting if already copied
          cp -rn src/app.py release/src/  # Adjust path to your app entry point (e.g., app.py or wsgi.py)
          cd release
          zip -r ../release.zip .

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip
          retention-days: 7  # Reduce retention to minimize storage usage

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
      actions: write  # Needed for artifact cleanup

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d ./release

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0CDBB6A05EB84D88A24353168A2EA668 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0CBB96E9A14248538A611623E41C9079 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BC5E8A5D5C85433A92C9D64BC6093231 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'blogging'
          slot-name: 'Production'
          package: ./release

      - name: Clean up artifacts
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
            });
            for (const artifact of artifacts.data.artifacts) {
              await github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id,
              });
            }