name: Build and deploy Python app to Azure Web App - blogging (No Artifacts)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: write  # Optional, in case you add cleanup later

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Identify changed files
        id: changed-files
        run: |
          git diff --name-only HEAD^ HEAD > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt

      - name: Package changed files and essentials
        run: |
          mkdir -p release
          # Copy only changed files and their dependencies (if needed)
          while IFS= read -r file; do
            if [ -f "$file" ]; then
              mkdir -p "release/$(dirname "$file")"
              cp "$file" "release/$file"
              # If a Python file changes, include dependent files (e.g., imports from src/)
              if [[ "$file" == *.py ]]; then
                grep -h "^import " "$file" | while read -r import_line; do
                  import_name=$(echo "$import_line" | awk '{print $2}' | cut -d'.' -f1)
                  find src/ -name "$import_name.py" -exec cp --parents {} release/ \;
                done
              fi
            fi
          done < changed_files.txt
          # Copy requirements.txt only if it changed (optional)
          if grep -q "requirements.txt" changed_files.txt; then
            cp requirements.txt release/
          fi
          cd release
          zip -r ../release.zip .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0CDBB6A05EB84D88A24353168A2EA668 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0CBB96E9A14248538A611623E41C9079 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BC5E8A5D5C85433A92C9D64BC6093231 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'blogging'
          slot-name: 'Production'
          package: ./release