# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - blogging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip


            # Second service principal login for fetching secrets from Key Vault
      - name: Login to Azure for Key Vault
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.KEYVAULT_CLIENTID }}
          tenant-id: ${{ secrets.KEYVAULT_TENANTID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0845F312B65649FB884B115CED156AE4 }}

           # Fetch secrets from Azure Key Vault using the second service principal
      - name: Fetch secrets from Azure Key Vault
        id: get-secrets
        uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: 'blogkeys'
          secrets: 'subkey,translatorendpoint,translatorlocation'

      # Set the secrets as environment variables
      - name: Set environment variables
        run: |
          echo "KEY=${{ steps.get-secrets.outputs.subkey }}" >> $GITHUB_ENV
          echo "ENDPOINT=${{ steps.get-secrets.outputs.translatorendpoint }}" >> $GITHUB_ENV
          echo "LOCATION=${{ steps.get-secrets.outputs.translatorlocation }}" >> $GITHUB_ENV


      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B05A5D265C284249932881F7E8D5141D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0001C408F5E04459B530A0259B79FD0B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0845F312B65649FB884B115CED156AE4 }}


      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'blogging'
          slot-name: 'Production'
          